micronaut:
  server:
    port: 8090
  application:
    name: bunnyMetrics

#
#datasources:
#  default:
#    validationQuery: SELECT 1 FROM DUAL
#    url: jdbc:trino://{trino.host}:{trino.port};
#    username: {trino.authentication.user}
#    password: ""

#velocityProperties:
#  - space.gobbling: bc


trino:
  host: "localhost"
  port: 8080
  authentication:
    user: "test"