micronaut:
  server:
    port: 8090
  application:
    name: bunnyMetrics

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

#velocityProperties:
#  - space.gobbling: bc

trino:
  host: "localhost"
  port: 8080
  authentication:
    user: "test"